language: python
python:
    - "2.7"
    - "3.6"
    - "3.7-dev"
install: make install-ci
script: make test-ci
after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
